# Generated by Django 4.0 on 2025-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backeryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('requests', models.TextField(blank=True)),
            ],
        ),
    ]
