# Generated by Django 4.0 on 2025-01-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backeryapp', '0003_prebooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_recipe',
            name='price_in_market',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
