# Generated by Django 4.0 on 2025-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backeryapp', '0004_bakery_recipe_price_in_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_recipe',
            name='price_in_market',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
    ]
